name: shellcheck
on: [push, pull_request]
jobs:
  sh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Lint
        run: shellcheck -x bin/fzd.sh install.sh uninstall.sh
